CREATE TABLE student(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(70) NOT NULL,
    correo VARCHAR(70) NOT NULL,
    fechaNacimiento DATE NOT NULL,
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE courses(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(70) NOT NULL,
    descripcion VARCHAR(70) NOT NULL,
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE enrollment(
    id INT AUTO_INCREMENT PRIMARY KEY,
    studentId INT,
    cursoId INT,
    fecha DATE,
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_student FOREIGN KEY (studentId) REFERENCES student(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_curso FOREIGN KEY (cursoId) REFERENCES courses (id) ON DELETE RESTRICT ON UPDATE CASCADE
);